pipeline
{
    agent  { label 'Mac' }
            // docker {
            //     image 'maven:3-alpine'
            //     args '-v /root/.m2:/root/.m2'
            // }
           tools { maven   'Apache Maven 3.8.6' }
    stages {
        stage('Initialize') {
            steps {sh '''echo "PATH = ${PATH}"'''}
                        }
        stage('Hello') {
            steps {sh 'mvn'}
                        }
    }
}
/*
pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
*/